SELECT ID,
	NAME,
	(
		CASE
			WHEN AGE BETWEEN 10 AND 20 THEN 'inerval #1'
			WHEN AGE > 20
			AND AGE < 24 THEN 'inerval #2'
			ELSE 'inerval #3'
		END
	) AS INTERVAL_INFO
FROM PERSON
ORDER BY INTERVAL_INFO